import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  client: {
    NEXT_PUBLIC_CHAIN_A_ID: z.coerce.number(),
    NEXT_PUBLIC_CHAIN_A_NAME: z.string().min(1),
    NEXT_PUBLIC_CHAIN_B_ID: z.coerce.number(),
    NEXT_PUBLIC_CHAIN_B_NAME: z.string().min(1),
    NEXT_PUBLIC_TRADE_ESCROW_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_USDC_CHAIN_A_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_USDC_CHAIN_B_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_USDC_ASSET_ID: z.string().min(1),
    NEXT_PUBLIC_TTBILL_CHAIN_A_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_TTBILL_CHAIN_B_ADDRESS: z.string().min(1),
    NEXT_PUBLIC_TTBILL_ASSET_ID: z.string().min(1),
    NEXT_PUBLIC_CHAIN_A_AUTH_API_URL: z.string().url(),
    NEXT_PUBLIC_CHAIN_A_BASE_RPC_URL: z.string().url(),
    NEXT_PUBLIC_CHAIN_A_BLOCK_EXPLORER_URL: z.string().url(),
  },
  experimental__runtimeEnv: {
    NEXT_PUBLIC_CHAIN_A_ID: process.env.NEXT_PUBLIC_CHAIN_A_ID,
    NEXT_PUBLIC_CHAIN_A_NAME: process.env.NEXT_PUBLIC_CHAIN_A_NAME,
    NEXT_PUBLIC_CHAIN_B_ID: process.env.NEXT_PUBLIC_CHAIN_B_ID,
    NEXT_PUBLIC_CHAIN_B_NAME: process.env.NEXT_PUBLIC_CHAIN_B_NAME,
    NEXT_PUBLIC_TRADE_ESCROW_ADDRESS: process.env.NEXT_PUBLIC_TRADE_ESCROW_ADDRESS,
    NEXT_PUBLIC_USDC_CHAIN_A_ADDRESS: process.env.NEXT_PUBLIC_USDC_CHAIN_A_ADDRESS,
    NEXT_PUBLIC_USDC_CHAIN_B_ADDRESS: process.env.NEXT_PUBLIC_USDC_CHAIN_B_ADDRESS,
    NEXT_PUBLIC_USDC_ASSET_ID: process.env.NEXT_PUBLIC_USDC_ASSET_ID,
    NEXT_PUBLIC_TTBILL_CHAIN_A_ADDRESS: process.env.NEXT_PUBLIC_TTBILL_CHAIN_A_ADDRESS,
    NEXT_PUBLIC_TTBILL_CHAIN_B_ADDRESS: process.env.NEXT_PUBLIC_TTBILL_CHAIN_B_ADDRESS,
    NEXT_PUBLIC_TTBILL_ASSET_ID: process.env.NEXT_PUBLIC_TTBILL_ASSET_ID,
    NEXT_PUBLIC_CHAIN_A_AUTH_API_URL: process.env.NEXT_PUBLIC_CHAIN_A_AUTH_API_URL,
    NEXT_PUBLIC_CHAIN_A_BASE_RPC_URL: process.env.NEXT_PUBLIC_CHAIN_A_BASE_RPC_URL,
    NEXT_PUBLIC_CHAIN_A_BLOCK_EXPLORER_URL: process.env.NEXT_PUBLIC_CHAIN_A_BLOCK_EXPLORER_URL,
  },
});
