/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  "271": {
    CPAMM: {
      address: "0x3F015117432f4E2e970D3B6b918F3B92D17eFC88",
      abi: [
        {
          type: "constructor",
          inputs: [
            { name: "_token0", type: "address", internalType: "address" },
            { name: "_token1", type: "address", internalType: "address" },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "addLiquidity",
          inputs: [
            { name: "_amount0", type: "uint256", internalType: "uint256" },
            { name: "_amount1", type: "uint256", internalType: "uint256" },
          ],
          outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [{ name: "", type: "address", internalType: "address" }],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "removeLiquidity",
          inputs: [{ name: "_shares", type: "uint256", internalType: "uint256" }],
          outputs: [
            { name: "amount0", type: "uint256", internalType: "uint256" },
            { name: "amount1", type: "uint256", internalType: "uint256" },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "reserve0",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "reserve1",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "swap",
          inputs: [
            { name: "_tokenIn", type: "address", internalType: "address" },
            { name: "_amountIn", type: "uint256", internalType: "uint256" },
          ],
          outputs: [{ name: "amountOut", type: "uint256", internalType: "uint256" }],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "token0",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "token1",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
      ],
    },
  },
} satisfies GenericContractsDeclaration;

export default deployedContracts;
