import { invoiceContracts } from "~~/config/invoice-config";

export const INVOICE_CONTRACT_ABI = [
  {
    type: "constructor",
    inputs: [{ name: "_admin", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  { type: "receive", stateMutability: "payable" },
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelInvoice",
    inputs: [{ name: "invoiceId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createInvoice",
    inputs: [
      { name: "recipient", type: "address", internalType: "address" },
      { name: "recipientChainId", type: "uint256", internalType: "uint256" },
      { name: "billingToken", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "creatorChainId", type: "uint256", internalType: "uint256" },
      { name: "creatorRefundAddress", type: "address", internalType: "address" },
      { name: "recipientRefundAddress", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "crossChainFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "exchangeRates",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getConversionAmount",
    inputs: [
      { name: "fromToken", type: "address", internalType: "address" },
      { name: "toToken", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getInvoiceDetails",
    inputs: [{ name: "invoiceId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "invoice",
        type: "tuple",
        internalType: "struct InvoicePayment.Invoice",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "creatorRefundAddress", type: "address", internalType: "address" },
          { name: "recipientRefundAddress", type: "address", internalType: "address" },
          { name: "creatorChainId", type: "uint256", internalType: "uint256" },
          { name: "recipientChainId", type: "uint256", internalType: "uint256" },
          { name: "billingToken", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "paymentToken", type: "address", internalType: "address" },
          { name: "paymentAmount", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum InvoicePayment.InvoiceStatus" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "paidAt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getMultipleInvoiceDetails",
    inputs: [{ name: "invoiceIds", type: "uint256[]", internalType: "uint256[]" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        internalType: "struct InvoicePayment.Invoice[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "creatorRefundAddress", type: "address", internalType: "address" },
          { name: "recipientRefundAddress", type: "address", internalType: "address" },
          { name: "creatorChainId", type: "uint256", internalType: "uint256" },
          { name: "recipientChainId", type: "uint256", internalType: "uint256" },
          { name: "billingToken", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "paymentToken", type: "address", internalType: "address" },
          { name: "paymentAmount", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum InvoicePayment.InvoiceStatus" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "paidAt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserAllInvoices",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "createdStartIndex", type: "uint256", internalType: "uint256" },
      { name: "createdEndIndex", type: "uint256", internalType: "uint256" },
      { name: "pendingStartIndex", type: "uint256", internalType: "uint256" },
      { name: "pendingEndIndex", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      {
        name: "createdInvoices",
        type: "tuple[]",
        internalType: "struct InvoicePayment.Invoice[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "creatorRefundAddress", type: "address", internalType: "address" },
          { name: "recipientRefundAddress", type: "address", internalType: "address" },
          { name: "creatorChainId", type: "uint256", internalType: "uint256" },
          { name: "recipientChainId", type: "uint256", internalType: "uint256" },
          { name: "billingToken", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "paymentToken", type: "address", internalType: "address" },
          { name: "paymentAmount", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum InvoicePayment.InvoiceStatus" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "paidAt", type: "uint256", internalType: "uint256" },
        ],
      },
      {
        name: "pendingInvoices",
        type: "tuple[]",
        internalType: "struct InvoicePayment.Invoice[]",
        components: [
          { name: "id", type: "uint256", internalType: "uint256" },
          { name: "creator", type: "address", internalType: "address" },
          { name: "recipient", type: "address", internalType: "address" },
          { name: "creatorRefundAddress", type: "address", internalType: "address" },
          { name: "recipientRefundAddress", type: "address", internalType: "address" },
          { name: "creatorChainId", type: "uint256", internalType: "uint256" },
          { name: "recipientChainId", type: "uint256", internalType: "uint256" },
          { name: "billingToken", type: "address", internalType: "address" },
          { name: "amount", type: "uint256", internalType: "uint256" },
          { name: "paymentToken", type: "address", internalType: "address" },
          { name: "paymentAmount", type: "uint256", internalType: "uint256" },
          { name: "status", type: "uint8", internalType: "enum InvoicePayment.InvoiceStatus" },
          { name: "createdAt", type: "uint256", internalType: "uint256" },
          { name: "paidAt", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserCreatedInvoiceCount",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserCreatedInvoices",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "startIndex", type: "uint256", internalType: "uint256" },
      { name: "endIndex", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserPendingInvoiceCount",
    inputs: [{ name: "user", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getUserPendingInvoices",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "startIndex", type: "uint256", internalType: "uint256" },
      { name: "endIndex", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getWhitelistedTokens",
    inputs: [],
    outputs: [
      { name: "", type: "address[]", internalType: "address[]" },
      { name: "", type: "string[]", internalType: "string[]" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "invoices",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "id", type: "uint256", internalType: "uint256" },
      { name: "creator", type: "address", internalType: "address" },
      { name: "recipient", type: "address", internalType: "address" },
      { name: "creatorRefundAddress", type: "address", internalType: "address" },
      { name: "recipientRefundAddress", type: "address", internalType: "address" },
      { name: "creatorChainId", type: "uint256", internalType: "uint256" },
      { name: "recipientChainId", type: "uint256", internalType: "uint256" },
      { name: "billingToken", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "paymentToken", type: "address", internalType: "address" },
      { name: "paymentAmount", type: "uint256", internalType: "uint256" },
      { name: "status", type: "uint8", internalType: "enum InvoicePayment.InvoiceStatus" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "paidAt", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "payInvoice",
    inputs: [
      { name: "invoiceId", type: "uint256", internalType: "uint256" },
      { name: "paymentToken", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "removeTokenFromWhitelist",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setAdmin",
    inputs: [{ name: "newAdmin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCrossChainFee",
    inputs: [{ name: "_crossChainFee", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setExchangeRate",
    inputs: [
      { name: "token1", type: "address", internalType: "address" },
      { name: "token2", type: "address", internalType: "address" },
      { name: "rate", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userCreatedInvoices",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "userPendingInvoices",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "whitelistToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "symbol", type: "string", internalType: "string" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "whitelistedTokens",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [
      { name: "isWhitelisted", type: "bool", internalType: "bool" },
      { name: "symbol", type: "string", internalType: "string" },
    ],
    stateMutability: "view",
  },
  { type: "function", name: "withdraw", inputs: [], outputs: [], stateMutability: "nonpayable" },
  {
    type: "function",
    name: "withdrawTokens",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CrossChainFeeUpdated",
    inputs: [{ name: "newFee", type: "uint256", indexed: false, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExchangeRateUpdated",
    inputs: [
      { name: "token1", type: "address", indexed: true, internalType: "address" },
      { name: "token2", type: "address", indexed: true, internalType: "address" },
      { name: "rate", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceCancelled",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "canceller", type: "address", indexed: true, internalType: "address" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoiceCreated",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "creatorRefundAddress", type: "address", indexed: true, internalType: "address" },
      { name: "recipientRefundAddress", type: "address", indexed: true, internalType: "address" },
      { name: "creatorChainId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "recipientChainId", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "billingToken", type: "address", indexed: false, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "InvoicePaid",
    inputs: [
      { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "payer", type: "address", indexed: true, internalType: "address" },
      { name: "paymentToken", type: "address", indexed: false, internalType: "address" },
      { name: "paymentAmount", type: "uint256", indexed: false, internalType: "uint256" },
      { name: "billingAmount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokenRemovedFromWhitelist",
    inputs: [{ name: "token", type: "address", indexed: true, internalType: "address" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "TokenWhitelisted",
    inputs: [
      { name: "token", type: "address", indexed: true, internalType: "address" },
      { name: "symbol", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
] as const;

export const INVOICE_CONTRACT_ADDRESS = invoiceContracts.invoiceContractAddress;
